'use client'

import { Inter } from '@next/font/google'

import { QueryClientProvider } from 'react-query'
import { ServerStylesheet } from './server-styles-sheet'
import { Header } from '@/components/header'
import * as S from '@/styles/layout.style'
import { queryClient } from '@/services/query-client'
import { Loading } from '@/components/Loading'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }: { children: any }) {
    return (
        <html lang="en" className={inter.className}>
            <head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body>
                <Loading>
                    <S.Container>
                        <Header />

                        <S.Content>
                            <ServerStylesheet>
                                <QueryClientProvider client={queryClient}>
                                    {children}
                                </QueryClientProvider>
                            </ServerStylesheet>
                        </S.Content>
                    </S.Container>
                </Loading>
            </body>
        </html>
    )
}
